'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dtsCategories
    Inherits DataSet
    
    Private tabletblInstruments As tblInstrumentsDataTable
    
    Private tabletblSubInstruments As tblSubInstrumentsDataTable
    
    Private tabletblSubInstruments2 As tblSubInstruments2DataTable
    
    Private relationdyo As DataRelation
    
    Private relationena As DataRelation
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("tblInstruments")) Is Nothing) Then
                Me.Tables.Add(New tblInstrumentsDataTable(ds.Tables("tblInstruments")))
            End If
            If (Not (ds.Tables("tblSubInstruments")) Is Nothing) Then
                Me.Tables.Add(New tblSubInstrumentsDataTable(ds.Tables("tblSubInstruments")))
            End If
            If (Not (ds.Tables("tblSubInstruments2")) Is Nothing) Then
                Me.Tables.Add(New tblSubInstruments2DataTable(ds.Tables("tblSubInstruments2")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property tblInstruments As tblInstrumentsDataTable
        Get
            Return Me.tabletblInstruments
        End Get
    End Property
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property tblSubInstruments As tblSubInstrumentsDataTable
        Get
            Return Me.tabletblSubInstruments
        End Get
    End Property
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property tblSubInstruments2 As tblSubInstruments2DataTable
        Get
            Return Me.tabletblSubInstruments2
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dtsCategories = CType(MyBase.Clone,dtsCategories)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("tblInstruments")) Is Nothing) Then
            Me.Tables.Add(New tblInstrumentsDataTable(ds.Tables("tblInstruments")))
        End If
        If (Not (ds.Tables("tblSubInstruments")) Is Nothing) Then
            Me.Tables.Add(New tblSubInstrumentsDataTable(ds.Tables("tblSubInstruments")))
        End If
        If (Not (ds.Tables("tblSubInstruments2")) Is Nothing) Then
            Me.Tables.Add(New tblSubInstruments2DataTable(ds.Tables("tblSubInstruments2")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tabletblInstruments = CType(Me.Tables("tblInstruments"),tblInstrumentsDataTable)
        If (Not (Me.tabletblInstruments) Is Nothing) Then
            Me.tabletblInstruments.InitVars
        End If
        Me.tabletblSubInstruments = CType(Me.Tables("tblSubInstruments"),tblSubInstrumentsDataTable)
        If (Not (Me.tabletblSubInstruments) Is Nothing) Then
            Me.tabletblSubInstruments.InitVars
        End If
        Me.tabletblSubInstruments2 = CType(Me.Tables("tblSubInstruments2"),tblSubInstruments2DataTable)
        If (Not (Me.tabletblSubInstruments2) Is Nothing) Then
            Me.tabletblSubInstruments2.InitVars
        End If
        Me.relationdyo = Me.Relations("dyo")
        Me.relationena = Me.Relations("ena")
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dtsCategories"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dtsCategories.xsd"
        Me.Locale = New System.Globalization.CultureInfo("el-GR")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tabletblInstruments = New tblInstrumentsDataTable
        Me.Tables.Add(Me.tabletblInstruments)
        Me.tabletblSubInstruments = New tblSubInstrumentsDataTable
        Me.Tables.Add(Me.tabletblSubInstruments)
        Me.tabletblSubInstruments2 = New tblSubInstruments2DataTable
        Me.Tables.Add(Me.tabletblSubInstruments2)
        Dim fkc As ForeignKeyConstraint
        fkc = New ForeignKeyConstraint("ena", New DataColumn() {Me.tabletblInstruments.instrumentColumn}, New DataColumn() {Me.tabletblSubInstruments.instrumentsColumn})
        Me.tabletblSubInstruments.Constraints.Add(fkc)
        fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None
        fkc.DeleteRule = System.Data.Rule.Cascade
        fkc.UpdateRule = System.Data.Rule.Cascade
        fkc = New ForeignKeyConstraint("dyo", New DataColumn() {Me.tabletblSubInstruments.subcategoryInstrumentColumn}, New DataColumn() {Me.tabletblSubInstruments2.subCategoryInstrumentColumn})
        Me.tabletblSubInstruments2.Constraints.Add(fkc)
        fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None
        fkc.DeleteRule = System.Data.Rule.Cascade
        fkc.UpdateRule = System.Data.Rule.Cascade
        Me.relationdyo = New DataRelation("dyo", New DataColumn() {Me.tabletblSubInstruments.subcategoryInstrumentColumn}, New DataColumn() {Me.tabletblSubInstruments2.subCategoryInstrumentColumn}, false)
        Me.Relations.Add(Me.relationdyo)
        Me.relationena = New DataRelation("ena", New DataColumn() {Me.tabletblInstruments.instrumentColumn}, New DataColumn() {Me.tabletblSubInstruments.instrumentsColumn}, false)
        Me.Relations.Add(Me.relationena)
    End Sub
    
    Private Function ShouldSerializetblInstruments() As Boolean
        Return false
    End Function
    
    Private Function ShouldSerializetblSubInstruments() As Boolean
        Return false
    End Function
    
    Private Function ShouldSerializetblSubInstruments2() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub tblInstrumentsRowChangeEventHandler(ByVal sender As Object, ByVal e As tblInstrumentsRowChangeEvent)
    
    Public Delegate Sub tblSubInstrumentsRowChangeEventHandler(ByVal sender As Object, ByVal e As tblSubInstrumentsRowChangeEvent)
    
    Public Delegate Sub tblSubInstruments2RowChangeEventHandler(ByVal sender As Object, ByVal e As tblSubInstruments2RowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblInstrumentsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columninstrument As DataColumn
        
        Friend Sub New()
            MyBase.New("tblInstruments")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property instrumentColumn As DataColumn
            Get
                Return Me.columninstrument
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As tblInstrumentsRow
            Get
                Return CType(Me.Rows(index),tblInstrumentsRow)
            End Get
        End Property
        
        Public Event tblInstrumentsRowChanged As tblInstrumentsRowChangeEventHandler
        
        Public Event tblInstrumentsRowChanging As tblInstrumentsRowChangeEventHandler
        
        Public Event tblInstrumentsRowDeleted As tblInstrumentsRowChangeEventHandler
        
        Public Event tblInstrumentsRowDeleting As tblInstrumentsRowChangeEventHandler
        
        Public Overloads Sub AddtblInstrumentsRow(ByVal row As tblInstrumentsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddtblInstrumentsRow(ByVal instrument As String) As tblInstrumentsRow
            Dim rowtblInstrumentsRow As tblInstrumentsRow = CType(Me.NewRow,tblInstrumentsRow)
            rowtblInstrumentsRow.ItemArray = New Object() {instrument}
            Me.Rows.Add(rowtblInstrumentsRow)
            Return rowtblInstrumentsRow
        End Function
        
        Public Function FindByinstrument(ByVal instrument As String) As tblInstrumentsRow
            Return CType(Me.Rows.Find(New Object() {instrument}),tblInstrumentsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As tblInstrumentsDataTable = CType(MyBase.Clone,tblInstrumentsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New tblInstrumentsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columninstrument = Me.Columns("instrument")
        End Sub
        
        Private Sub InitClass()
            Me.columninstrument = New DataColumn("instrument", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columninstrument)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columninstrument}, true))
            Me.columninstrument.AllowDBNull = false
            Me.columninstrument.Unique = true
        End Sub
        
        Public Function NewtblInstrumentsRow() As tblInstrumentsRow
            Return CType(Me.NewRow,tblInstrumentsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New tblInstrumentsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(tblInstrumentsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.tblInstrumentsRowChangedEvent) Is Nothing) Then
                RaiseEvent tblInstrumentsRowChanged(Me, New tblInstrumentsRowChangeEvent(CType(e.Row,tblInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.tblInstrumentsRowChangingEvent) Is Nothing) Then
                RaiseEvent tblInstrumentsRowChanging(Me, New tblInstrumentsRowChangeEvent(CType(e.Row,tblInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.tblInstrumentsRowDeletedEvent) Is Nothing) Then
                RaiseEvent tblInstrumentsRowDeleted(Me, New tblInstrumentsRowChangeEvent(CType(e.Row,tblInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.tblInstrumentsRowDeletingEvent) Is Nothing) Then
                RaiseEvent tblInstrumentsRowDeleting(Me, New tblInstrumentsRowChangeEvent(CType(e.Row,tblInstrumentsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovetblInstrumentsRow(ByVal row As tblInstrumentsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblInstrumentsRow
        Inherits DataRow
        
        Private tabletblInstruments As tblInstrumentsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tabletblInstruments = CType(Me.Table,tblInstrumentsDataTable)
        End Sub
        
        Public Property instrument As String
            Get
                Return CType(Me(Me.tabletblInstruments.instrumentColumn),String)
            End Get
            Set
                Me(Me.tabletblInstruments.instrumentColumn) = value
            End Set
        End Property
        
        Public Function GettblSubInstrumentsRows() As tblSubInstrumentsRow()
            Return CType(Me.GetChildRows(Me.Table.ChildRelations("ena")),tblSubInstrumentsRow())
        End Function
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblInstrumentsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As tblInstrumentsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As tblInstrumentsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As tblInstrumentsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstrumentsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columninstruments As DataColumn
        
        Private columnsubcategoryInstrument As DataColumn
        
        Friend Sub New()
            MyBase.New("tblSubInstruments")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property instrumentsColumn As DataColumn
            Get
                Return Me.columninstruments
            End Get
        End Property
        
        Friend ReadOnly Property subcategoryInstrumentColumn As DataColumn
            Get
                Return Me.columnsubcategoryInstrument
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As tblSubInstrumentsRow
            Get
                Return CType(Me.Rows(index),tblSubInstrumentsRow)
            End Get
        End Property
        
        Public Event tblSubInstrumentsRowChanged As tblSubInstrumentsRowChangeEventHandler
        
        Public Event tblSubInstrumentsRowChanging As tblSubInstrumentsRowChangeEventHandler
        
        Public Event tblSubInstrumentsRowDeleted As tblSubInstrumentsRowChangeEventHandler
        
        Public Event tblSubInstrumentsRowDeleting As tblSubInstrumentsRowChangeEventHandler
        
        Public Overloads Sub AddtblSubInstrumentsRow(ByVal row As tblSubInstrumentsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddtblSubInstrumentsRow(ByVal parenttblInstrumentsRowByena As tblInstrumentsRow, ByVal subcategoryInstrument As String) As tblSubInstrumentsRow
            Dim rowtblSubInstrumentsRow As tblSubInstrumentsRow = CType(Me.NewRow,tblSubInstrumentsRow)
            rowtblSubInstrumentsRow.ItemArray = New Object() {parenttblInstrumentsRowByena(0), subcategoryInstrument}
            Me.Rows.Add(rowtblSubInstrumentsRow)
            Return rowtblSubInstrumentsRow
        End Function
        
        Public Function FindBysubcategoryInstrument(ByVal subcategoryInstrument As String) As tblSubInstrumentsRow
            Return CType(Me.Rows.Find(New Object() {subcategoryInstrument}),tblSubInstrumentsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As tblSubInstrumentsDataTable = CType(MyBase.Clone,tblSubInstrumentsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New tblSubInstrumentsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columninstruments = Me.Columns("instruments")
            Me.columnsubcategoryInstrument = Me.Columns("subcategoryInstrument")
        End Sub
        
        Private Sub InitClass()
            Me.columninstruments = New DataColumn("instruments", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columninstruments)
            Me.columnsubcategoryInstrument = New DataColumn("subcategoryInstrument", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnsubcategoryInstrument)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnsubcategoryInstrument}, true))
            Me.columnsubcategoryInstrument.AllowDBNull = false
            Me.columnsubcategoryInstrument.Unique = true
        End Sub
        
        Public Function NewtblSubInstrumentsRow() As tblSubInstrumentsRow
            Return CType(Me.NewRow,tblSubInstrumentsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New tblSubInstrumentsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(tblSubInstrumentsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.tblSubInstrumentsRowChangedEvent) Is Nothing) Then
                RaiseEvent tblSubInstrumentsRowChanged(Me, New tblSubInstrumentsRowChangeEvent(CType(e.Row,tblSubInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.tblSubInstrumentsRowChangingEvent) Is Nothing) Then
                RaiseEvent tblSubInstrumentsRowChanging(Me, New tblSubInstrumentsRowChangeEvent(CType(e.Row,tblSubInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.tblSubInstrumentsRowDeletedEvent) Is Nothing) Then
                RaiseEvent tblSubInstrumentsRowDeleted(Me, New tblSubInstrumentsRowChangeEvent(CType(e.Row,tblSubInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.tblSubInstrumentsRowDeletingEvent) Is Nothing) Then
                RaiseEvent tblSubInstrumentsRowDeleting(Me, New tblSubInstrumentsRowChangeEvent(CType(e.Row,tblSubInstrumentsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovetblSubInstrumentsRow(ByVal row As tblSubInstrumentsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstrumentsRow
        Inherits DataRow
        
        Private tabletblSubInstruments As tblSubInstrumentsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tabletblSubInstruments = CType(Me.Table,tblSubInstrumentsDataTable)
        End Sub
        
        Public Property instruments As String
            Get
                Try 
                    Return CType(Me(Me.tabletblSubInstruments.instrumentsColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletblSubInstruments.instrumentsColumn) = value
            End Set
        End Property
        
        Public Property subcategoryInstrument As String
            Get
                Return CType(Me(Me.tabletblSubInstruments.subcategoryInstrumentColumn),String)
            End Get
            Set
                Me(Me.tabletblSubInstruments.subcategoryInstrumentColumn) = value
            End Set
        End Property
        
        Public Property tblInstrumentsRow As tblInstrumentsRow
            Get
                Return CType(Me.GetParentRow(Me.Table.ParentRelations("ena")),tblInstrumentsRow)
            End Get
            Set
                Me.SetParentRow(value, Me.Table.ParentRelations("ena"))
            End Set
        End Property
        
        Public Function IsinstrumentsNull() As Boolean
            Return Me.IsNull(Me.tabletblSubInstruments.instrumentsColumn)
        End Function
        
        Public Sub SetinstrumentsNull()
            Me(Me.tabletblSubInstruments.instrumentsColumn) = System.Convert.DBNull
        End Sub
        
        Public Function GettblSubInstruments2Rows() As tblSubInstruments2Row()
            Return CType(Me.GetChildRows(Me.Table.ChildRelations("dyo")),tblSubInstruments2Row())
        End Function
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstrumentsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As tblSubInstrumentsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As tblSubInstrumentsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As tblSubInstrumentsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstruments2DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columncode As DataColumn
        
        Private columnsubCategoryInstrument As DataColumn
        
        Private columnsubCategoryInstrument2 As DataColumn
        
        Friend Sub New()
            MyBase.New("tblSubInstruments2")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property codeColumn As DataColumn
            Get
                Return Me.columncode
            End Get
        End Property
        
        Friend ReadOnly Property subCategoryInstrumentColumn As DataColumn
            Get
                Return Me.columnsubCategoryInstrument
            End Get
        End Property
        
        Friend ReadOnly Property subCategoryInstrument2Column As DataColumn
            Get
                Return Me.columnsubCategoryInstrument2
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As tblSubInstruments2Row
            Get
                Return CType(Me.Rows(index),tblSubInstruments2Row)
            End Get
        End Property
        
        Public Event tblSubInstruments2RowChanged As tblSubInstruments2RowChangeEventHandler
        
        Public Event tblSubInstruments2RowChanging As tblSubInstruments2RowChangeEventHandler
        
        Public Event tblSubInstruments2RowDeleted As tblSubInstruments2RowChangeEventHandler
        
        Public Event tblSubInstruments2RowDeleting As tblSubInstruments2RowChangeEventHandler
        
        Public Overloads Sub AddtblSubInstruments2Row(ByVal row As tblSubInstruments2Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddtblSubInstruments2Row(ByVal parenttblSubInstrumentsRowBydyo As tblSubInstrumentsRow, ByVal subCategoryInstrument2 As String) As tblSubInstruments2Row
            Dim rowtblSubInstruments2Row As tblSubInstruments2Row = CType(Me.NewRow,tblSubInstruments2Row)
            rowtblSubInstruments2Row.ItemArray = New Object() {Nothing, parenttblSubInstrumentsRowBydyo(1), subCategoryInstrument2}
            Me.Rows.Add(rowtblSubInstruments2Row)
            Return rowtblSubInstruments2Row
        End Function
        
        Public Function FindBycode(ByVal code As Integer) As tblSubInstruments2Row
            Return CType(Me.Rows.Find(New Object() {code}),tblSubInstruments2Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As tblSubInstruments2DataTable = CType(MyBase.Clone,tblSubInstruments2DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New tblSubInstruments2DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columncode = Me.Columns("code")
            Me.columnsubCategoryInstrument = Me.Columns("subCategoryInstrument")
            Me.columnsubCategoryInstrument2 = Me.Columns("subCategoryInstrument2")
        End Sub
        
        Private Sub InitClass()
            Me.columncode = New DataColumn("code", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncode)
            Me.columnsubCategoryInstrument = New DataColumn("subCategoryInstrument", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnsubCategoryInstrument)
            Me.columnsubCategoryInstrument2 = New DataColumn("subCategoryInstrument2", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnsubCategoryInstrument2)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columncode}, true))
            Me.columncode.AutoIncrement = true
            Me.columncode.AllowDBNull = false
            Me.columncode.Unique = true
        End Sub
        
        Public Function NewtblSubInstruments2Row() As tblSubInstruments2Row
            Return CType(Me.NewRow,tblSubInstruments2Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New tblSubInstruments2Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(tblSubInstruments2Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.tblSubInstruments2RowChangedEvent) Is Nothing) Then
                RaiseEvent tblSubInstruments2RowChanged(Me, New tblSubInstruments2RowChangeEvent(CType(e.Row,tblSubInstruments2Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.tblSubInstruments2RowChangingEvent) Is Nothing) Then
                RaiseEvent tblSubInstruments2RowChanging(Me, New tblSubInstruments2RowChangeEvent(CType(e.Row,tblSubInstruments2Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.tblSubInstruments2RowDeletedEvent) Is Nothing) Then
                RaiseEvent tblSubInstruments2RowDeleted(Me, New tblSubInstruments2RowChangeEvent(CType(e.Row,tblSubInstruments2Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.tblSubInstruments2RowDeletingEvent) Is Nothing) Then
                RaiseEvent tblSubInstruments2RowDeleting(Me, New tblSubInstruments2RowChangeEvent(CType(e.Row,tblSubInstruments2Row), e.Action))
            End If
        End Sub
        
        Public Sub RemovetblSubInstruments2Row(ByVal row As tblSubInstruments2Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstruments2Row
        Inherits DataRow
        
        Private tabletblSubInstruments2 As tblSubInstruments2DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tabletblSubInstruments2 = CType(Me.Table,tblSubInstruments2DataTable)
        End Sub
        
        Public Property code As Integer
            Get
                Return CType(Me(Me.tabletblSubInstruments2.codeColumn),Integer)
            End Get
            Set
                Me(Me.tabletblSubInstruments2.codeColumn) = value
            End Set
        End Property
        
        Public Property subCategoryInstrument As String
            Get
                Try 
                    Return CType(Me(Me.tabletblSubInstruments2.subCategoryInstrumentColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletblSubInstruments2.subCategoryInstrumentColumn) = value
            End Set
        End Property
        
        Public Property subCategoryInstrument2 As String
            Get
                Try 
                    Return CType(Me(Me.tabletblSubInstruments2.subCategoryInstrument2Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletblSubInstruments2.subCategoryInstrument2Column) = value
            End Set
        End Property
        
        Public Property tblSubInstrumentsRow As tblSubInstrumentsRow
            Get
                Return CType(Me.GetParentRow(Me.Table.ParentRelations("dyo")),tblSubInstrumentsRow)
            End Get
            Set
                Me.SetParentRow(value, Me.Table.ParentRelations("dyo"))
            End Set
        End Property
        
        Public Function IssubCategoryInstrumentNull() As Boolean
            Return Me.IsNull(Me.tabletblSubInstruments2.subCategoryInstrumentColumn)
        End Function
        
        Public Sub SetsubCategoryInstrumentNull()
            Me(Me.tabletblSubInstruments2.subCategoryInstrumentColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IssubCategoryInstrument2Null() As Boolean
            Return Me.IsNull(Me.tabletblSubInstruments2.subCategoryInstrument2Column)
        End Function
        
        Public Sub SetsubCategoryInstrument2Null()
            Me(Me.tabletblSubInstruments2.subCategoryInstrument2Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstruments2RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As tblSubInstruments2Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As tblSubInstruments2Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As tblSubInstruments2Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
