'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dtsSmallInstr
    Inherits DataSet
    
    Private tabletblInstruments As tblInstrumentsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("tblInstruments")) Is Nothing) Then
                Me.Tables.Add(New tblInstrumentsDataTable(ds.Tables("tblInstruments")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property tblInstruments As tblInstrumentsDataTable
        Get
            Return Me.tabletblInstruments
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dtsSmallInstr = CType(MyBase.Clone,dtsSmallInstr)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("tblInstruments")) Is Nothing) Then
            Me.Tables.Add(New tblInstrumentsDataTable(ds.Tables("tblInstruments")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tabletblInstruments = CType(Me.Tables("tblInstruments"),tblInstrumentsDataTable)
        If (Not (Me.tabletblInstruments) Is Nothing) Then
            Me.tabletblInstruments.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dtsSmallInstr"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dtsSmallInstr.xsd"
        Me.Locale = New System.Globalization.CultureInfo("el-GR")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tabletblInstruments = New tblInstrumentsDataTable
        Me.Tables.Add(Me.tabletblInstruments)
    End Sub
    
    Private Function ShouldSerializetblInstruments() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub tblInstrumentsRowChangeEventHandler(ByVal sender As Object, ByVal e As tblInstrumentsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblInstrumentsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columninstrument As DataColumn
        
        Friend Sub New()
            MyBase.New("tblInstruments")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property instrumentColumn As DataColumn
            Get
                Return Me.columninstrument
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As tblInstrumentsRow
            Get
                Return CType(Me.Rows(index),tblInstrumentsRow)
            End Get
        End Property
        
        Public Event tblInstrumentsRowChanged As tblInstrumentsRowChangeEventHandler
        
        Public Event tblInstrumentsRowChanging As tblInstrumentsRowChangeEventHandler
        
        Public Event tblInstrumentsRowDeleted As tblInstrumentsRowChangeEventHandler
        
        Public Event tblInstrumentsRowDeleting As tblInstrumentsRowChangeEventHandler
        
        Public Overloads Sub AddtblInstrumentsRow(ByVal row As tblInstrumentsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddtblInstrumentsRow(ByVal instrument As String) As tblInstrumentsRow
            Dim rowtblInstrumentsRow As tblInstrumentsRow = CType(Me.NewRow,tblInstrumentsRow)
            rowtblInstrumentsRow.ItemArray = New Object() {instrument}
            Me.Rows.Add(rowtblInstrumentsRow)
            Return rowtblInstrumentsRow
        End Function
        
        Public Function FindByinstrument(ByVal instrument As String) As tblInstrumentsRow
            Return CType(Me.Rows.Find(New Object() {instrument}),tblInstrumentsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As tblInstrumentsDataTable = CType(MyBase.Clone,tblInstrumentsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New tblInstrumentsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columninstrument = Me.Columns("instrument")
        End Sub
        
        Private Sub InitClass()
            Me.columninstrument = New DataColumn("instrument", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columninstrument)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columninstrument}, true))
            Me.columninstrument.AllowDBNull = false
            Me.columninstrument.Unique = true
        End Sub
        
        Public Function NewtblInstrumentsRow() As tblInstrumentsRow
            Return CType(Me.NewRow,tblInstrumentsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New tblInstrumentsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(tblInstrumentsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.tblInstrumentsRowChangedEvent) Is Nothing) Then
                RaiseEvent tblInstrumentsRowChanged(Me, New tblInstrumentsRowChangeEvent(CType(e.Row,tblInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.tblInstrumentsRowChangingEvent) Is Nothing) Then
                RaiseEvent tblInstrumentsRowChanging(Me, New tblInstrumentsRowChangeEvent(CType(e.Row,tblInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.tblInstrumentsRowDeletedEvent) Is Nothing) Then
                RaiseEvent tblInstrumentsRowDeleted(Me, New tblInstrumentsRowChangeEvent(CType(e.Row,tblInstrumentsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.tblInstrumentsRowDeletingEvent) Is Nothing) Then
                RaiseEvent tblInstrumentsRowDeleting(Me, New tblInstrumentsRowChangeEvent(CType(e.Row,tblInstrumentsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovetblInstrumentsRow(ByVal row As tblInstrumentsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblInstrumentsRow
        Inherits DataRow
        
        Private tabletblInstruments As tblInstrumentsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tabletblInstruments = CType(Me.Table,tblInstrumentsDataTable)
        End Sub
        
        Public Property instrument As String
            Get
                Return CType(Me(Me.tabletblInstruments.instrumentColumn),String)
            End Get
            Set
                Me(Me.tabletblInstruments.instrumentColumn) = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblInstrumentsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As tblInstrumentsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As tblInstrumentsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As tblInstrumentsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
