'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dtssubcombo2
    Inherits DataSet
    
    Private tabletblSubInstruments2 As tblSubInstruments2DataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("tblSubInstruments2")) Is Nothing) Then
                Me.Tables.Add(New tblSubInstruments2DataTable(ds.Tables("tblSubInstruments2")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property tblSubInstruments2 As tblSubInstruments2DataTable
        Get
            Return Me.tabletblSubInstruments2
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dtssubcombo2 = CType(MyBase.Clone,dtssubcombo2)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("tblSubInstruments2")) Is Nothing) Then
            Me.Tables.Add(New tblSubInstruments2DataTable(ds.Tables("tblSubInstruments2")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tabletblSubInstruments2 = CType(Me.Tables("tblSubInstruments2"),tblSubInstruments2DataTable)
        If (Not (Me.tabletblSubInstruments2) Is Nothing) Then
            Me.tabletblSubInstruments2.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dtssubcombo2"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dtssubcombo2.xsd"
        Me.Locale = New System.Globalization.CultureInfo("el-GR")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tabletblSubInstruments2 = New tblSubInstruments2DataTable
        Me.Tables.Add(Me.tabletblSubInstruments2)
    End Sub
    
    Private Function ShouldSerializetblSubInstruments2() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub tblSubInstruments2RowChangeEventHandler(ByVal sender As Object, ByVal e As tblSubInstruments2RowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstruments2DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columncode As DataColumn
        
        Private columnsubCategoryInstrument As DataColumn
        
        Private columnsubCategoryInstrument2 As DataColumn
        
        Friend Sub New()
            MyBase.New("tblSubInstruments2")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property codeColumn As DataColumn
            Get
                Return Me.columncode
            End Get
        End Property
        
        Friend ReadOnly Property subCategoryInstrumentColumn As DataColumn
            Get
                Return Me.columnsubCategoryInstrument
            End Get
        End Property
        
        Friend ReadOnly Property subCategoryInstrument2Column As DataColumn
            Get
                Return Me.columnsubCategoryInstrument2
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As tblSubInstruments2Row
            Get
                Return CType(Me.Rows(index),tblSubInstruments2Row)
            End Get
        End Property
        
        Public Event tblSubInstruments2RowChanged As tblSubInstruments2RowChangeEventHandler
        
        Public Event tblSubInstruments2RowChanging As tblSubInstruments2RowChangeEventHandler
        
        Public Event tblSubInstruments2RowDeleted As tblSubInstruments2RowChangeEventHandler
        
        Public Event tblSubInstruments2RowDeleting As tblSubInstruments2RowChangeEventHandler
        
        Public Overloads Sub AddtblSubInstruments2Row(ByVal row As tblSubInstruments2Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddtblSubInstruments2Row(ByVal subCategoryInstrument As String, ByVal subCategoryInstrument2 As String) As tblSubInstruments2Row
            Dim rowtblSubInstruments2Row As tblSubInstruments2Row = CType(Me.NewRow,tblSubInstruments2Row)
            rowtblSubInstruments2Row.ItemArray = New Object() {Nothing, subCategoryInstrument, subCategoryInstrument2}
            Me.Rows.Add(rowtblSubInstruments2Row)
            Return rowtblSubInstruments2Row
        End Function
        
        Public Function FindBycode(ByVal code As Integer) As tblSubInstruments2Row
            Return CType(Me.Rows.Find(New Object() {code}),tblSubInstruments2Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As tblSubInstruments2DataTable = CType(MyBase.Clone,tblSubInstruments2DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New tblSubInstruments2DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columncode = Me.Columns("code")
            Me.columnsubCategoryInstrument = Me.Columns("subCategoryInstrument")
            Me.columnsubCategoryInstrument2 = Me.Columns("subCategoryInstrument2")
        End Sub
        
        Private Sub InitClass()
            Me.columncode = New DataColumn("code", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncode)
            Me.columnsubCategoryInstrument = New DataColumn("subCategoryInstrument", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnsubCategoryInstrument)
            Me.columnsubCategoryInstrument2 = New DataColumn("subCategoryInstrument2", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnsubCategoryInstrument2)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columncode}, true))
            Me.columncode.AutoIncrement = true
            Me.columncode.AllowDBNull = false
            Me.columncode.Unique = true
        End Sub
        
        Public Function NewtblSubInstruments2Row() As tblSubInstruments2Row
            Return CType(Me.NewRow,tblSubInstruments2Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New tblSubInstruments2Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(tblSubInstruments2Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.tblSubInstruments2RowChangedEvent) Is Nothing) Then
                RaiseEvent tblSubInstruments2RowChanged(Me, New tblSubInstruments2RowChangeEvent(CType(e.Row,tblSubInstruments2Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.tblSubInstruments2RowChangingEvent) Is Nothing) Then
                RaiseEvent tblSubInstruments2RowChanging(Me, New tblSubInstruments2RowChangeEvent(CType(e.Row,tblSubInstruments2Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.tblSubInstruments2RowDeletedEvent) Is Nothing) Then
                RaiseEvent tblSubInstruments2RowDeleted(Me, New tblSubInstruments2RowChangeEvent(CType(e.Row,tblSubInstruments2Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.tblSubInstruments2RowDeletingEvent) Is Nothing) Then
                RaiseEvent tblSubInstruments2RowDeleting(Me, New tblSubInstruments2RowChangeEvent(CType(e.Row,tblSubInstruments2Row), e.Action))
            End If
        End Sub
        
        Public Sub RemovetblSubInstruments2Row(ByVal row As tblSubInstruments2Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstruments2Row
        Inherits DataRow
        
        Private tabletblSubInstruments2 As tblSubInstruments2DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tabletblSubInstruments2 = CType(Me.Table,tblSubInstruments2DataTable)
        End Sub
        
        Public Property code As Integer
            Get
                Return CType(Me(Me.tabletblSubInstruments2.codeColumn),Integer)
            End Get
            Set
                Me(Me.tabletblSubInstruments2.codeColumn) = value
            End Set
        End Property
        
        Public Property subCategoryInstrument As String
            Get
                Try 
                    Return CType(Me(Me.tabletblSubInstruments2.subCategoryInstrumentColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletblSubInstruments2.subCategoryInstrumentColumn) = value
            End Set
        End Property
        
        Public Property subCategoryInstrument2 As String
            Get
                Try 
                    Return CType(Me(Me.tabletblSubInstruments2.subCategoryInstrument2Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletblSubInstruments2.subCategoryInstrument2Column) = value
            End Set
        End Property
        
        Public Function IssubCategoryInstrumentNull() As Boolean
            Return Me.IsNull(Me.tabletblSubInstruments2.subCategoryInstrumentColumn)
        End Function
        
        Public Sub SetsubCategoryInstrumentNull()
            Me(Me.tabletblSubInstruments2.subCategoryInstrumentColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IssubCategoryInstrument2Null() As Boolean
            Return Me.IsNull(Me.tabletblSubInstruments2.subCategoryInstrument2Column)
        End Function
        
        Public Sub SetsubCategoryInstrument2Null()
            Me(Me.tabletblSubInstruments2.subCategoryInstrument2Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class tblSubInstruments2RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As tblSubInstruments2Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As tblSubInstruments2Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As tblSubInstruments2Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
